# Generated by Django 4.0.3 on 2022-04-30 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('tran_date', models.DateField(verbose_name='Transaction Date')),
                ('tran_category', models.CharField(max_length=50, verbose_name='Transaction Category')),
                ('credit_amount', models.DecimalField(decimal_places=5, default=0, max_digits=10, verbose_name='Credit Amount')),
                ('debit_amount', models.DecimalField(decimal_places=5, default=0, max_digits=10, verbose_name='Debit Amount')),
            ],
            options={
                'db_table': 'transactions',
            },
        ),
    ]
